version: "3.9"

services:
  frontend:
    image: ccnrad/climatelens_ui-frontend:latest
    ports:
      - target: 5173
        published: 5173
        protocol: tcp
        mode: host
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
