name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build-and-push:
    name: Build Docker Image and push to GHCR
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Check out the files
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASSWRD }}

      - name: Build Docker image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cxconrad/climatelens_ui:latest
