name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    name: Build Docker Image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      # Repository klonen
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Set up Docker Buildx with the correct driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # ✅ Fix: Use docker-container driver

      # Optional: Run tests before building
      - name: Run tests
        run: npm test
        continue-on-error: true  # Falls Tests fehlschlagen, wird der Build fortgesetzt

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASSWRD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cxconrad/climatelens_ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Cleanup to free up space
      - name: Cleanup
        run: docker system prune -af
