name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    name: Build Docker Image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      # Repository klonen
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Node.js installieren und Abhängigkeiten prüfen 
      # - name: Install Node.js and dependencies
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: npm ci 

      # Tests vor dem Build ausführen
      # Falls `npm ci` auskommentiert bleibt, kann dieser Schritt fehlschlagen,
      # falls Tests auf fehlende Abhängigkeiten treffen.
      - name: Run tests
        run: npm test
        continue-on-error: true  # Falls Tests fehlschlagen, wird der Build fortgesetzt

      # Docker-Login für GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker-Image bauen und pushen
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cxconrad/climatelens_ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Speicherplatz freigeben
      - name: Cleanup
        run: docker system prune -af
